let animaux = [
  {
    id: 1,
    name: "Bulbizarre",
    hp: 25,
    cp: 5,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
    types: ["Plante", "Poisson"],
    created: new Date(),
  },
  {
    id: 2,
    name: "Salamèche",
    hp: 28,
    cp: 6,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
    types: ["Feu"],
    created: new Date(),
  },
  {
    id: 3,
    name: "Carapuce",
    hp: 21,
    cp: 4,
    picture:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
    types: ["Eau"],
    created: new Date(),
  },

  // {
  //   id: 4,
  //   name: "Aspicot",
  //   hp: 16,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 5,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 6,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 7,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 8,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 9,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 10,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 11,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
  // {
  //   id: 12,
  //   name: "Bulbizarre",
  //   hp: 25,
  //   cp: 5,
  //   picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  //   types: ["Plante", "Poisson"],
  //   created: new Date(),
  // },
];
